<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <RootNamespace>StorybrewEditor</RootNamespace>
        <AssemblyName>StorybrewEditor</AssemblyName>
        <Platforms>x86;x64</Platforms>
        <Version>1.94</Version>
        <TargetFramework>net9.0-windows</TargetFramework>
        <PublishReadyToRun>true</PublishReadyToRun>
        <UseWpf>true</UseWpf>
        <LangVersion>default</LangVersion>
        <DebugType>embedded</DebugType>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup>
        <StartupObject>StorybrewEditor.Program</StartupObject>
        <ApplicationIcon>icon.ico</ApplicationIcon>
        <Product>storybrew editor</Product>
        <Company>storybrew</Company>
        <Copyright>Copyright © Damnae 2016</Copyright>
        <AnalysisLevel>latest-recommended</AnalysisLevel>
        <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
        <Optimize>True</Optimize>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
        <Optimize>True</Optimize>
        <DefineConstants>TRACE;TARGET_64BIT</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
        <DefineConstants>TRACE;TARGET_64BIT</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="icon.ico"/>
        <EmbeddedResource Include="Resources.zip"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\brewlib\bass\$(Platform)\*.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\brewlib\brewlib.csproj"/>
        <ProjectReference Include="..\common\common.csproj"/>
        <ProjectReference Include="..\tiny\tiny.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ErrorProne.NET.CoreAnalyzers" Version="0.8.0-beta.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="ErrorProne.NET.Structs" Version="0.6.1-beta.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0"/>
        <PackageReference Include="NfdExt" Version="1.2.4"/>
        <PackageReference Include="SkipLocalsInit" Version="1.1.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>