<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Version>1.2.0</Version>
        <AssemblyName>Tiny</AssemblyName>
        <Copyright>Copyright © Damnae 2021</Copyright>
        <RootNamespace>Tiny</RootNamespace>
        <Company>storybrew</Company>
        <EnableNETAnalyzers>True</EnableNETAnalyzers>
        <AnalysisLevel>latest-recommended</AnalysisLevel>
        <LangVersion>default</LangVersion>
        <DebugType>embedded</DebugType>
        <Platforms>AnyCPU;x64</Platforms>
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <Optimize>True</Optimize>
        <DebugSymbols>false</DebugSymbols>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
        <Optimize>True</Optimize>
        <DebugSymbols>false</DebugSymbols>
        <DefineConstants>TARGET_64BIT</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
        <DefineConstants>TARGET_64BIT</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ErrorProne.NET.CoreAnalyzers" Version="0.7.0-beta.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="ErrorProne.NET.Structs" Version="0.6.1-beta.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="SkipLocalsInit" Version="1.1.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="ZLinq" Version="1.4.10"/>
    </ItemGroup>

</Project>