namespace BrewLib.Graphics.Shaders;

using OpenTK.Graphics.OpenGL;

public static class ShaderUtil
{
    public static string GetString(this ActiveUniformType type) => type switch
    {
        ActiveUniformType.Int => "int",
        ActiveUniformType.UnsignedInt => "uint",
        ActiveUniformType.Float => "float",
        ActiveUniformType.Double => "double",
        ActiveUniformType.FloatVec2 => "vec2",
        ActiveUniformType.FloatVec3 => "vec3",
        ActiveUniformType.FloatVec4 => "vec4",
        ActiveUniformType.IntVec2 => "ivec2",
        ActiveUniformType.IntVec3 => "ivec3",
        ActiveUniformType.IntVec4 => "ivec4",
        ActiveUniformType.Bool => "bool",
        ActiveUniformType.BoolVec2 => "bvec2",
        ActiveUniformType.BoolVec3 => "bvec3",
        ActiveUniformType.BoolVec4 => "bvec4",
        ActiveUniformType.FloatMat2 => "mat2",
        ActiveUniformType.FloatMat3 => "mat3",
        ActiveUniformType.FloatMat4 => "mat4",
        ActiveUniformType.Sampler1D => "sampler1D",
        ActiveUniformType.Sampler2D => "sampler2D",
        ActiveUniformType.Sampler3D => "sampler3D",
        ActiveUniformType.SamplerCube => "samplerCube",
        ActiveUniformType.Sampler1DShadow => "sampler1DShadow",
        ActiveUniformType.Sampler2DShadow => "sampler2DShadow",
        ActiveUniformType.Sampler2DRect => "sampler2DRect",
        ActiveUniformType.Sampler2DRectShadow => "sampler2DRectShadow",
        ActiveUniformType.FloatMat2x3 => "mat2x3",
        ActiveUniformType.FloatMat2x4 => "mat2x4",
        ActiveUniformType.FloatMat3x2 => "mat3x2",
        ActiveUniformType.FloatMat3x4 => "mat3x4",
        ActiveUniformType.FloatMat4x2 => "mat4x2",
        ActiveUniformType.FloatMat4x3 => "mat4x3",
        ActiveUniformType.Sampler1DArray => "sampler1DArray",
        ActiveUniformType.Sampler2DArray => "sampler2DArray",
        ActiveUniformType.SamplerBuffer => "samplerBuffer",
        ActiveUniformType.Sampler1DArrayShadow => "sampler1DArrayShadow",
        ActiveUniformType.Sampler2DArrayShadow => "sampler2DArrayShadow",
        ActiveUniformType.SamplerCubeShadow => "samplerCubeShadow",
        ActiveUniformType.UnsignedIntVec2 => "uvec2",
        ActiveUniformType.UnsignedIntVec3 => "uvec3",
        ActiveUniformType.UnsignedIntVec4 => "uvec4",
        ActiveUniformType.IntSampler1D => "isampler1D",
        ActiveUniformType.IntSampler2D => "isampler2D",
        ActiveUniformType.IntSampler3D => "isampler3D",
        ActiveUniformType.IntSamplerCube => "isamplerCube",
        ActiveUniformType.IntSampler2DRect => "isampler2DRect",
        ActiveUniformType.IntSampler1DArray => "isampler1DArray",
        ActiveUniformType.IntSampler2DArray => "isampler2DArray",
        ActiveUniformType.IntSamplerBuffer => "isamplerBuffer",
        ActiveUniformType.UnsignedIntSampler1D => "usampler1D",
        ActiveUniformType.UnsignedIntSampler2D => "usampler2D",
        ActiveUniformType.UnsignedIntSampler3D => "usampler3D",
        ActiveUniformType.UnsignedIntSamplerCube => "usamplerCube",
        ActiveUniformType.UnsignedIntSampler2DRect => "usampler2DRect",
        ActiveUniformType.UnsignedIntSampler1DArray => "usampler1DArray",
        ActiveUniformType.UnsignedIntSampler2DArray => "usampler2DArray",
        ActiveUniformType.UnsignedIntSamplerBuffer => "usamplerBuffer",
        ActiveUniformType.DoubleVec2 => "dvec2",
        ActiveUniformType.DoubleVec3 => "dvec3",
        ActiveUniformType.DoubleVec4 => "dvec4",
        ActiveUniformType.SamplerCubeMapArray => "samplerCubeArray",
        ActiveUniformType.SamplerCubeMapArrayShadow => "samplerCubeArrayShadow",
        ActiveUniformType.IntSamplerCubeMapArray => "isamplerCubeArray",
        ActiveUniformType.UnsignedIntSamplerCubeMapArray => "usamplerCubeArray",
        ActiveUniformType.Image1D => "image1D",
        ActiveUniformType.Image2D => "image2D",
        ActiveUniformType.Image3D => "image3D",
        ActiveUniformType.Image2DRect => "image2DRect",
        ActiveUniformType.ImageCube => "imageCube",
        ActiveUniformType.ImageBuffer => "imageBuffer",
        ActiveUniformType.Image1DArray => "image1DArray",
        ActiveUniformType.Image2DArray => "image2DArray",
        ActiveUniformType.ImageCubeMapArray => "imageCubeArray",
        ActiveUniformType.Image2DMultisample => "image2DMS",
        ActiveUniformType.Image2DMultisampleArray => "image2DMSArray",
        ActiveUniformType.IntImage1D => "iimage1D",
        ActiveUniformType.IntImage2D => "iimage2D",
        ActiveUniformType.IntImage3D => "iimage3D",
        ActiveUniformType.IntImage2DRect => "iimage2DRect",
        ActiveUniformType.IntImageCube => "iimageCube",
        ActiveUniformType.IntImageBuffer => "iimageBuffer",
        ActiveUniformType.IntImage1DArray => "iimage1DArray",
        ActiveUniformType.IntImage2DArray => "iimage2DArray",
        ActiveUniformType.IntImageCubeMapArray => "iimageCubeArray",
        ActiveUniformType.IntImage2DMultisample => "iimage2DMS",
        ActiveUniformType.IntImage2DMultisampleArray => "iimage2DMSArray",
        ActiveUniformType.UnsignedIntImage1D => "uimage1D",
        ActiveUniformType.UnsignedIntImage2D => "uimage2D",
        ActiveUniformType.UnsignedIntImage3D => "uimage3D",
        ActiveUniformType.UnsignedIntImage2DRect => "uimage2DRect",
        ActiveUniformType.UnsignedIntImageCube => "uimageCube",
        ActiveUniformType.UnsignedIntImageBuffer => "uimageBuffer",
        ActiveUniformType.UnsignedIntImage1DArray => "uimage1DArray",
        ActiveUniformType.UnsignedIntImage2DArray => "uimage2DArray",
        ActiveUniformType.UnsignedIntImageCubeMapArray => "uimageCubeArray",
        ActiveUniformType.UnsignedIntImage2DMultisample => "uimage2DMS",
        ActiveUniformType.UnsignedIntImage2DMultisampleArray => "uimage2DMSArray",
        ActiveUniformType.Sampler2DMultisample => "sampler2DMS",
        ActiveUniformType.IntSampler2DMultisample => "isampler2DMS",
        ActiveUniformType.UnsignedIntSampler2DMultisample => "usampler2DMS",
        ActiveUniformType.Sampler2DMultisampleArray => "sampler2DMSArray",
        ActiveUniformType.IntSampler2DMultisampleArray => "isampler2DMSArray",
        ActiveUniformType.UnsignedIntSampler2DMultisampleArray => "usampler2DMSArray",
        ActiveUniformType.UnsignedIntAtomicCounter => "atomic_uint",
        _ => "",
    };

    public static bool IsFlatType(this ActiveUniformType type)
        => type is ActiveUniformType.Int or ActiveUniformType.UnsignedInt or ActiveUniformType.Bool or ActiveUniformType.IntVec2 or ActiveUniformType.IntVec3 or ActiveUniformType.IntVec4 or ActiveUniformType.UnsignedIntVec2 or ActiveUniformType.UnsignedIntVec3 or ActiveUniformType.UnsignedIntVec4 or ActiveUniformType.BoolVec2 or ActiveUniformType.BoolVec3 or ActiveUniformType.BoolVec4;
}